version: "3"
services:
  angular:
    image: yomogan/3_angular:test_angular
    ports:
      - "4200:4200"
  express:
    image: yomogan/3_express:test_express
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
