version: "3"
		services:
		  express:
        image: yomogan/3_test_expressjs_ghub:latest
        ports:
          - "3000:3000"
        links:
              - mongo
		  angular:
        image: yomogan/3_test_angular_ghub:latest
        ports:
          - "4200:4200" 
		  mongo:
        image: mongo
        ports:
          - "27017:27017"
